### ISSUE TITLE
TIF-File does not open

### ISSUE THREAD

**Issue by rmadner** [d2phap/ImageGlass#1181]
### System information:
 - Windows OS version: 1607 Build 14393.4704 64-bit
 - ImageGlass version: 8.3.11.21

### To Reproduce
1. open File from explorer
2. 
3. 
4. 

### Actual behavior:

ImageGlass says "loading", Message disappears, no image opened, no error message
other TIF-Files can be opened without problems

### Expected behavior:

image opened or at least an error message

### Additional context:

File cannot be uploaded, TIF is not supported...

**Comment by fire-eggs** [comment]
>File cannot be uploaded, TIF is not supported...

Zip the TIF file, then upload the zip.

**Comment by rmadner** [comment]
[imageglass.zip](https://github.com/d2phap/ImageGlass/files/7647628/imageglass.zip)
Inside are 3 examples, that do not work with ImageGlass, as well as a screenshot. 

Any idea, what's the cause?

**Comment by rmadner** [comment]
In the preview/thumbnails it can be displayed, but it's impossible to get it displayed in ImageGlass. Seems that it's been opened, because you can click "open with" or "edit image" and it is displayed e.g. in paint. This is my workaround, but I am not happy with it.

**Comment by fire-eggs** [comment]
MS Photos can't view "WelcomeFax.tif" either. Here is the output from ImageMagick:

```
E:\temp\ig_1181>magick identify WelcomeFax.tif
identify: Not a TIFF or MDI file, bad magic number 17220 (0x4344). `WelcomeFax.tif' @ error/tiff.c/TIFFErrors/599.

E:\temp\ig_1181>magick identify Muster.tif
identify: Unknown field with tag 1 (0x1) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/963.
identify: Unknown field with tag 32928 (0x80a0) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/963.
identify: ASCII value for tag "DocumentName" does not end in null byte. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/963.
identify: Muster.tif: Null count for "Tag 32928" (type 4, writecount -3, passcount 1). `_TIFFVSetField' @ error/tiff.c/TIFFErrors/599.
```

So "WelcomeFax.tif" isn't a TIFF file at all; I see the first three characters in the file are "DCS", perhaps it is a dcs file? Anyway, whatever it is, it's not supported by ImageMagick, Windows, or ImageGlass ...

It's possible that ImageGlass would be happy with "Muster.tif" if the errors above were fixed. It _is_ annoying that the thumbnail can be seen, but not the image. I'll try to dig further into that.

**Comment by rmadner** [comment]
Well, "WelcomeFax.tif" seems to be anything, but not a TIFF, that's for sure.

I did some searches about muster.tif on myself. Strange: one dcs-converter says it must be TIFF, others take it an convert it to any image-type you like...

Did you find out anything new so far?

**Comment by rmadner** [comment]
Sorry if I am being inconvenient: 

> MS Photos can't view "WelcomeFax.tif" either. Here is the output from ImageMagick:
> 
> ```
> E:\temp\ig_1181>magick identify WelcomeFax.tif
> identify: Not a TIFF or MDI file, bad magic number 17220 (0x4344). `WelcomeFax.tif' @ error/tiff.c/TIFFErrors/599.
> 
> E:\temp\ig_1181>magick identify Muster.tif
> identify: Unknown field with tag 1 (0x1) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/963.
> identify: Unknown field with tag 32928 (0x80a0) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/963.
> identify: ASCII value for tag "DocumentName" does not end in null byte. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/963.
> identify: Muster.tif: Null count for "Tag 32928" (type 4, writecount -3, passcount 1). `_TIFFVSetField' @ error/tiff.c/TIFFErrors/599.
> ```
> 
> So "WelcomeFax.tif" isn't a TIFF file at all; I see the first three characters in the file are "DCS", perhaps it is a dcs file? Anyway, whatever it is, it's not supported by ImageMagick, Windows, or ImageGlass ...
> 
> It's possible that ImageGlass would be happy with "Muster.tif" if the errors above were fixed. It _is_ annoying that the thumbnail can be seen, but not the image. I'll try to dig further into that.

Sorry if I am being inconvenient - do you see this as a bug and try to fix it?

**Comment by d2phap** [comment]
Hi @rmadner 
The issue is open means I will still look into it. It depends on the difficulty, you can see there are issues remain for months or years, too.

As @fire-eggs mentioned above, ImageGlass uses Magick.NET to read and decode image files. We will need to contact to ImageMagick forks,...

**Comment by rmadner** [comment]
Hi @d2phap 
Allright, I understand now... i did not see, that the problem lies in another piece of software, that you can't control. I try to be patient and hope that these problems don't occur too often (ImageGlass will be used by about 2500 Users), until you have a solution.

Thanks for the quick answer!

**Comment by d2phap** [comment]
[ImageGlass 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) fixes the issue of the TIFF format with invalid tag `32928` (file Muster.tif).

**Comment by d2phap** [comment]
[ImageGlass 8.8](https://github.com/d2phap/ImageGlass/releases/tag/8.8.3.28) fixes the issue of the TIFF format with invalid tag 32928 (file Muster.tif).
