### ISSUE TITLE
Some programs in Windows10 Startmenu display as ImageGlass Icon

### ISSUE THREAD

**Issue by XiaofengdiZhu** [d2phap/ImageGlass#480]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have searched [open](https://github.com/d2phap/ImageGlass/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%90%9E+bug%22) and [closed](https://github.com/d2phap/ImageGlass/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+label%3A%22%F0%9F%90%9E+bug%22+) issues to ensure it has not already been reported

### System information:
 - Windows OS version: Windows10 Professional 1809
 - ImageGlass version: 6.0.12.29

### To Reproduce
1. Add "Adobe Acrobat DC" or "Evernote" to the Startmenu.

### Actual behavior:
I can't see some programs' correct icons in the Startmenu like "Adobe Acrobat DC" and "Evernote".

### Expected behavior:
See correct icons in the Startmenu.

### Screenshots:
![F43W8A.png](https://s1.ax1x.com/2018/12/31/F43W8A.png)
![F43fgI.png](https://s1.ax1x.com/2018/12/31/F43fgI.png)

### Additional context:
No

**Comment by s8321414** [comment]
I can reproduce for Adobe Acrobat DC.

**Comment by Otiel** [comment]
Also have this issue after installing ImageGlass, on the Start Menu main list (without pinning Adobe Reader DC):

![image](https://user-images.githubusercontent.com/3851902/50656861-e39ffc00-0f94-11e9-9e9c-f7f2dc4166eb.png)

**Comment by XiaofengdiZhu** [comment]
After times of rebooting, 

> I believe the problem is with Evernote, Adobe, etc.
> [For instance](https://discussion.evernote.com/topic/110965-problem-with-the-evernote-desktop-icon-on-taskbar-for-windows-10/)

After using the solution in the link and times of rebooting, this problem has been solved.

**Comment by d2phap** [comment]
thanks for confirmation

**Comment by lbux** [comment]
@d2phap After several months this still seems to be an issue. However, it is not hijacking my Adobe Evernote, etc icons. It is hijacking all Windows store applications (Camera, Calculator, Windows Terminal, etc). The originally intended icons are present everywhere but Windows search. There is no way to modify the "shortcuts" because Windows store apps do not have shortcuts from what I can tell. I've followed all the advice on [this thread](https://groups.google.com/forum/#!topic/imageglass/oPYXNnf3mrs) and all the advice on this thread. I would really like to know a way to revert back to the original icons.

![image](https://user-images.githubusercontent.com/30765968/84734756-98926280-af56-11ea-8849-66c879f08778.png)
![image](https://user-images.githubusercontent.com/30765968/84734760-9af4bc80-af56-11ea-943c-a5e205d50d5a.png)

**Comment by d2phap** [comment]
@lbux 
Can you try delete (or rename) `Ext-Icons` folder in ImageGlass installed folder, then
- Open Windows Settings, change default photo viewer to MS Photos
- Open ImageGlass Settings > File Type Association
- Click on Set as Default photo viewer button
- Go back to Windows Settings, set ImageGlass as default photo viewer

**Comment by lbux** [comment]
@d2phap Thank you for getting back to me so quickly. I've tried all that and nothing works. Even if I delete ImageGlass, restart my PC, and then look for all traces of anything related to ImageGlass using a search application and delete those files, the problem persists.

**Comment by cactysman** [comment]
I've been running into the same issue since first installing ImageGlass and it's still an issue with version `8.0.12.8`.

**Comment by lbux** [comment]
> I've been running into the same issue since first installing ImageGlass and it's still an issue with version `8.0.12.8`.

The issue has been persistent since my initial post; however, the issue seems to be more so Windows related than ImageGlass related. I've also had the issue on instances not running ImageGlass. [Google File Stream](https://www.reddit.com/r/Windows10/comments/8jx5ym/google_drive_file_stream_causing_uwp_icons_to/) (which I have installed) also seems to cause a similar issue.

**Comment by dgonyier** [comment]
I see this issue with WIndows Store app icons. Running ImageGlass 8.5.1.22 x64 installed from MSI installer, if that matters.

**Comment by dgonyier** [comment]
Seems to only happen when using the search bar to find an app. Just scrolling through the start menu or pinning to the start menu both show the correct icon. I blame Cortana :)

**Comment by lbux** [comment]
I ended up upgrading to Windows 11 (22000.434) and the issue has not yet presented itself. Nothing I did on Windows 10 fixed it, so perhaps the issue was fixed with something Microsoft did from 10->11
